# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    http_method_override: false
    handle_all_throwables: true
 
    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    #trusted_hosts: '%env(TRUSTED_HOSTS)%'
    # See https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#defaults
    trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto' ]
    #trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto', 'x-forwarded-host' ]

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    #session:
    #    handler_id: null
    #    cookie_secure: auto
    #    cookie_samesite: lax
    #    storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    http_client:
        scoped_clients:
            # use scoped client to ease mock on functional tests
            security.authorization.client:
                base_uri: '%env(OIDC_SERVER_URL_INTERNAL)%/'

when@test:
    framework:
        test: true
        #session:
        #    storage_factory_id: session.storage.factory.mock_file
