# See full configuration: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#full-default-bundle-configuration
zenstruck_foundry:
    orm:
        reset:
            entity_managers: [ 'default' ]
