# yaml-language-server: $schema=https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/github-workflow.json
name: Check

on:
  workflow_call:
    inputs:
      url:
        type: string
        description: URL

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Run local k6 test
        uses: grafana/k6-action@v0.3.1
        with:
          filename: k6/script.js
          flags: --out json=results.json
        env:
          TARGET: ${{ inputs.url }}
